import Foundation
import OpenAPIRuntime
import OpenAPIURLSession

// This target hosts code generated by Apple's Swift OpenAPI Generator.
// The shim ensures the target has at least one source file and provides
// a place for convenience initializers/extensions in the future.

