name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}

      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode.app/Contents/Developer"

      - name: Swift version
        run: swift --version

      - name: Build (triggers OpenAPI generation)
        run: swift build -v

      - name: Test
        run: swift test -q

      - name: Emit generated sources summary
        if: always()
        run: |
          echo "Generated files:" || true
          find .build/plugins/outputs -name '*.swift' -maxdepth 6 | sed 's#^# - #'
