name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}

      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode.app/Contents/Developer"

      - name: Swift version
        run: swift --version

      - name: Lint OpenAPI (Spectral)
        uses: stoplightio/spectral-action@v0.8.13
        with:
          file_glob: openapi/**/*.yaml

      - name: Build OpenAPI docs (ReDocly)
        run: |
          npm install -g @redocly/cli@latest
          mkdir -p build
          redocly build-docs openapi/layoutkit.yaml -o build/layoutkit.html

      - name: Upload OpenAPI docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-docs
          path: build/layoutkit.html

      - name: Build (triggers OpenAPI generation)
        run: swift build -v

      - name: Test
        run: swift test -q

      - name: Emit generated sources summary
        if: always()
        run: |
          echo "Generated files:" || true
          find .build/plugins/outputs -name '*.swift' -maxdepth 6 | sed 's#^# - #'
